/*
Gerador de Lero Lero
*/

var dicionario_filosofia = {
	conjuncoes: new Array(
		"Assim, ",
		"Por outro lado, ",
		"Assim mesmo, ",
		"No entanto, não podemos esquecer que ",
		"Do mesmo modo, ",
		"A tradição epistemológica prova que ",
		"Nunca é demais lembrar o peso e o significado destes problemas, uma vez que ",
		"E o mundo, tal como é, fundamenta que ",
		"Acima de tudo, é fundamental ressaltar que ",
		"O incentivo ao avanço tecnológico, assim como ",
		"Não obstante, ",
		"Todas estas questões, devidamente ponderadas, levantam dúvidas se ",
		"Porque além do rizoma ser um ente que nadifica ele também é ",
		"Então, se se supõe que a experiência sensorial vem da substancia, então ",
		"Ainda assim, existem dúvidas a respeito de como ",
		"É importante enfatizar que ",
		"Todavia, ",
		"A nível metafísico, ",
		"O empenho em analisar ",
		"Percebemos, cada vez mais, que ",
		"Na ontologia, ",
		"É importante questionar o quanto ",
		"Neste sentido, ",
		"Evidentemente, ",
		"Por conseguinte, ",
		"É claro que ",
		"Podemos já vislumbrar o modo pelo qual ",
		"Desta maneira, ",
		"O cuidado em identificar a realidade do eu mesmo faz com que ",
		"A criação de critérios que nos auxiliam a lidar com "
	),
	substantivos: new Array(
			"a densidade do nisus em contraposição à própria essencia ",
			"a complexidade dos estudos de Guattari ",
			"a contínua expansão de nossa atividade ôntica ",
			"a estrutura atual da hermenêutica ",
			"o novo modelo ontológico/metafísico ",
			"o desenvolvimento contínuo de distintas formas de substanciação ",
			"o constante estado de estranheza ",
			"a consolidação da forma própria do ser ",
			"o sentido de incerteza rizomático e imanente ",
			"o início da efetividade geral da Physis ",
			"a problemática tipicamente existencialista que se vê em Sartre ",
			"a capacidade de efetuação do tempo como uma conjunção do tempo e do ser ",
			"o inconsciente edípico pssicanalítico ",
			"o desejo de gozo e a volta ao útero ",
			"a inveja do falo ",
			"o aumento do diálogo entre a poesia e o artista ",
			"a crescente integração diferencial da essência ",
			"a necessidade de morte da mônada Leibniziana ",
			"a relação entre o corpo e o espírito imanente que se vê nos trabalhos de Artaud ",
			"o surgimento da filosofia na grécia na problemática orientalista ",
			"o pós-estruturalismo semiótico francês como partida do dasein ",
			"a abertura e o fechamento da dobra deleuziana ",
			"o encontro de uma paixão triste na concepção spinozana ",
			"a determinação clara da vontade de poder ",
			"a adoção de uma nova estética ",
			"a redução da ética de Epicuro face os questionamentos de Eriúgena ",
			"a percepção da dificuldade da subjetividade como um vazio que se preenche enquanto é ele mesmo e a si próprio ",
			"o entendimento da proposta da filosofia transcendental como crítica à metafísica ",
			"o consenso sobre a necessidade da tradução de eon e phenestai ",
			"o julgamento imparcial do caminho da verdade absoluta "
		),
	verbos:  new Array(
			"nos obriga à análise ",
			"cumpre um papel essencial na formulação ",
			"exige a precisão e a definição ",
			"auxilia a preparação e a composição ",
			"garante a contribuição de um grupo importante na determinação ",
			"assume importantes posições no estabelecimento ",
			"facilita a criação ",
			"obstaculiza a apreciação da importância ",
			"oferece uma interessante oportunidade para verificação ",
			"acarreta um processo de reformulação e modernização ",
			"pode nos levar a considerar a reestruturação ",
			"representa uma abertura para a melhoria ",
			"ainda não demonstrou convincentemente que vai participar na recriação ",
			"talvez venha a ressaltar a relatividade ",
			"prepara-nos para enfrentar situações atípicas decorrentes ",
			"maximiza as possibilidades por causa ",
			"desafia a capacidade de equalização ",
			"põe em cheque o objeto ",
			"é uma das consequências ",
			"promove a alavancagem ",
			"não pode mais se dissociar ",
			"possibilita uma melhor visão geral ",
			"estimula o desejo ",
			"aponta para a evolução ",
			"faz parte de um processo de auto decisão ",
			"causa impacto na concepção incestual ",
			"apresenta tendências no sentido de aprovar o sentido ",
			"estende o alcance e a importância ",
			"deve passar por modificações independentemente ",
			"afeta positivamente a correta previsão "
		),
	complementos: new Array(
			"das condições pissicanalíticas e obscuras exigidas.",
			"das diretrizes de desenvolvimento da filosofia mística.",
			"do sistema de participação geral das coisas no mundo.",
			"da postura do tempo e da matéria com relação às suas atribuições essenciais na natureza.",
			"de uma pssicanálise mais bergsoniana.",
			"das direções do sentido da posição de Pascal no estudo das probabilidades.",
			"do sistema de negação da linguagem que corresponde à primeiridade, secundariedade e terceiridade de Peirce.",
			"das condições do objeto difuso na lógica moderna apropriadas.",
			"dos conceitos a serem criados.",
			"das formas de súbito-ação do corpo, não como corpo inerte, mas corpo morto dentro de si.",
			"dos paradigmas da análise estética.",
			"das verticalidades entre as hierarquias da substância.",
			"do processo de comunicação entre a ideia e o ser como um todo.",
			"dos métodos utilizados na dialética dualista de Descartes.",
			"de todos os recursos funcionais envolvidos.",
			"dos níveis de ação do homem.",
			"da gestão do corpo do qual fazemos parte.",
			"das cosmologias convencionais.",
			"de alternativas às soluções das igrejas ortodoxas.",
			"dos procedimentos normalmente adotados nesse tipo de julgamento.",
			"dos conhecimentos éticos morais de Kant para atingir a excelência.",
			"do fluxo de informações semióticas.",
			"do levantamento das variáveis envolvidas.",
			"das diversas correntes de pensamento.",
			"do impacto da agilidade do sentido e do nisus Humeano.",
			"das regras de conduta normativas da ética teleológica.",
			"do modo setorial.",
			"do eterno retorno.",
			"do sentido ôntico.",
			"do nada e do ente."
		)
};